name: Security Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: security-audit-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

permissions:
  contents: read

jobs:
  audit:
    name: Cargo Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Install cargo-audit
        uses: taiki-e/install-action@0bc4cd8a3e21db4cb9519857377b0c8c5e150de5  # v2
        with:
          tool: cargo-audit

      - name: Security audit (advisories)
        run: cargo audit --deny warnings
        continue-on-error: true

      - name: Check for yanked dependencies
        run: cargo audit --deny yanked
